repos:
  - repo: local
    hooks:
      - id: generate
        name: Run 'npm run generate'
        entry: npm run generate
        language: system
        pass_filenames: false
        stages: [push]

      - id: lint
        name: Run 'npm run lint'
        entry: npm run lint
        language: system
        pass_filenames: false
        stages: [push]
